[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
example_client = "7ecjG7TZ1ynYvmtLCh7uXa6UJ6aiSCF1NtgquhY8pZ2d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "test_keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
upgradeable = true

[test.validator]
url = "https://api.devnet.solana.com"
[[test.validator.clone]]
address = "VRFCBePmGTpZ234BhbzNNzmyg39Rgdd6VgdfhHwKypU"
